# Generated by Django 4.2.30 on 2026-09-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('transaction_date', models.DateField()),
                ('country', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('net_amount', models.FloatField()),
                ('vat_rate', models.FloatField()),
                ('vat_amount', models.FloatField()),
                ('gross_amount', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
