# Generated by Django 4.2.30 on 2026-09-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_country_alter_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
